# openEuler 各架构 release 包与 repo 配置
# 变量 RELEASE_URL_<ARCH> 与 REPO_FILE_URL 由 mk_rootfs 读取

# x86_64
RELEASE_URL_x86_64=http://repo.openeuler.org/openEuler-24.03-LTS-SP3/everything/x86_64/Packages/openEuler-release-24.03LTS_SP3-57.oe2403sp3.x86_64.rpm
# aarch64
RELEASE_URL_aarch64=http://repo.openeuler.org/openEuler-24.03-LTS-SP3/everything/aarch64/Packages/openEuler-release-24.03LTS_SP3-57.oe2403sp3.aarch64.rpm

# 通用 repo 文件（generic.repo 对各架构通用）
REPO_FILE_URL=https://raw.atomgit.com/src-openeuler/openEuler-repos/raw/openEuler-24.03-LTS-SP3/generic.repo
